Fix some if conditions; replace return with break

diff --git a/templates/configmap_approve-csrs-sh.yaml b/templates/configmap_approve-csrs-sh.yaml
--- a/templates/configmap_approve-csrs-sh.yaml
+++ b/templates/configmap_approve-csrs-sh.yaml
@@ -34,62 +34,62 @@ data:
       CSR_NAME=$(echo "$CSR" | jq -r '.metadata.name')
 
       # Ensure spec.username field is of the form 'system:node:<nodeName>'
-      if ! jq -e '.spec.username | select(. == "system:node:*")' "$CSR" > /dev/null; then
+      if ! echo $CSR | jq -e '. | select(.spec.username | startswith("system:node:"))' > /dev/null; then
         echo "The CSR doesn't have a field .spec.username in the form of system:node:<nodeName>. Won't approve."
-        return
+        break
       fi
 
       # Ensure spec.groups array contains 'system:nodes'
-      if ! jq -e '.spec.groups[] | select(. == "system:nodes")' "$CSR" > /dev/null; then
+      if ! echo $CSR | jq -e '.spec.groups[] | select(. == "system:nodes")' > /dev/null; then
         echo "The CSR doesn't contain system:nodes in spec.groups array. Won't approve."
-        return
+        break
       fi
 
       # Ensure spec.usages contains 'server auth'
-      if ! jq -e '.spec.usages[] | select(. == "server auth")' "$CSR" > /dev/null; then
+      if ! echo $CSR | jq -e '.spec.usages[] | select(. == "server auth")' > /dev/null; then
         echo "The CSR doesn't contain 'server auth' in spec.usages array. Won't approve."
-        return
+        break
       fi
 
       # Ensure spec.usages optionally only contains 'digital signature' or 'key encipherment'
       allowed_elements=("server auth" "digital signature" "key encipherment")
-      invalid_elements=$(jq -r '.spec.usages[]' "$CSR" | grep -v -F -x "${allowed_elements[@]}")
+      invalid_elements=$(echo $CSR | jq -r '.spec.usages[]' | grep -v -E "$(printf '%s|' "${allowed_elements[@]}" | sed 's/|$//')")
 
       if [[ -n $invalid_elements ]]; then
-        echo "The CSR contains invalid elements in spec.usages array: $invalid_elements"
-        echo "Won't approve."
-        return
+        echo "The CSR contains invalid elements in spec.usages array: $(printf '%s|' "${invalid_elements[@]}" | sed 's/|$//'). Won't approve."
+        break
       fi
 
       # Read 'Subject Alternative Name' field of x509 certificate into array
-      IFS=',' read -r -a SUBJECT_ALTERNATIVE_NAME_ARRAY <<< $(echo $CSR_LIST | jq -r '.[0].spec.request' | base64 -d | openssl req -text -noout | grep -A 1 "Subject Alternative Name" | sed -n '2p')
+      IFS=',' read -r -a SUBJECT_ALTERNATIVE_NAME_ARRAY <<< $(echo $CSR | jq -r '.spec.request' | base64 -d | openssl req -text -noout | grep -A 1 "Subject Alternative Name" | sed -n '2p')
       SUBJECT_ALTERNATIVE_NAME_ARRAY_LENGTH=${#SUBJECT_ALTERNATIVE_NAME_ARRAY[@]}
 
       # Ensure 'Subject Alternative Name' field of x509 certificate only consists of DNS and IP Address
       if (( SUBJECT_ALTERNATIVE_NAME_ARRAY_LENGTH != 2 )); then
         echo "Invalid number of subject alternative names. Only 2 allowed. Won't approve."
-        return
+        break
       fi
 
       for subjAltName in "${SUBJECT_ALTERNATIVE_NAME_ARRAY[@]}"; do
-        IFS=':' read -r -a SPLIT_ARRAY <<< echo $subjAltName
+        IFS=':' read -r -a SPLIT_ARRAY <<< "$subjAltName"
         IP_ADDRESS_OF_NODE=""
         if [[ ${SPLIT_ARRAY[0]} == *"DNS"* ]] ; then
           # Ensure node exists in the cluster
-          HTTP_CODE=$(curl -w '%{http_code}' -s -o /dev/null --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -X GET "Content-Type: application/json" -H "Accept: application/json" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/nodes/${SPLIT_ARRAY[1]})
+          HTTP_CODE=$(curl -w '%{http_code}' -s -o /dev/null --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -X GET "Content-Type: application/json" -H "Accept: application/json" "https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/nodes/${SPLIT_ARRAY[1]}")
           if (( HTTP_CODE != 200 )); then
             echo "Cluster has no node ${SPLIT_ARRAY[1]}. Subject Alternative Name DNS invalid. Won't approve."
-            return
+            break 2
           fi
-          IP_ADDRESS_OF_NODE=$(curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -X GET "Content-Type: application/json" -H "Accept: application/json" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/nodes/${SPLIT_ARRAY[1]} | jq -r '.status.addresses[0].address')
+          IP_ADDRESS_OF_NODE=$(curl -s --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -X GET "Content-Type: application/json" -H "Accept: application/json" "https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/api/v1/nodes/${SPLIT_ARRAY[1]}" | jq -r '.status.addresses[0].address')
         elif [[ ${SPLIT_ARRAY[0]} == *"IP Address"* ]] ; then
           # Ensure IP address of CSR belongs to node
           if [[ "$IP_ADDRESS_OF_NODE" != "${SPLIT_ARRAY[1]}" ]]; then
             echo "Subject Alternative Name IP Address doesn't match IP address of node. Won't approve."
-            return
+            break 2
+          fi
         else
           echo "Subject Alternative Name contains invalid element. Won't approve."
-          return
+          break 2
         fi
       done
 
